# Generated by Django 3.1.1 on 2021-07-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_no', models.TextField(max_length=2000, null=True, unique=True)),
                ('subtotal', models.TextField(default='0', max_length=2000, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('discount', models.TextField(default='0', max_length=2000, null=True)),
                ('paid_amount', models.TextField(default='0', max_length=2000, null=True)),
                ('discount_reason', models.TextField(blank=True, max_length=2000, null=True)),
                ('discount_type', models.TextField(default='Ks', max_length=2000)),
                ('due_amount', models.TextField(blank=True, default='0', max_length=2000)),
                ('payment_status', models.TextField(blank=True, default='Unpaid', max_length=2000)),
                ('status', models.TextField(default='Processing', max_length=2000, null=True)),
                ('note', models.TextField(default='', max_length=2000, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_fullfilled', models.BooleanField(default=False)),
                ('get_voucher', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.TextField(default='0', max_length=2000, null=True)),
                ('number_of_fullfilled', models.TextField(default='0', max_length=2000, null=True)),
                ('primary_price', models.TextField(default='0', max_length=2000, null=True)),
                ('primary_price_yuan', models.TextField(default='0', max_length=2000, null=True)),
                ('sale_price', models.TextField(default='0', max_length=2000, null=True)),
                ('subtotal', models.TextField(default='0', max_length=2000, null=True)),
                ('margin', models.TextField(default='0', max_length=2000, null=True)),
                ('profit', models.TextField(default='0', max_length=2000, null=True)),
                ('name', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.TextField(blank=True, max_length=2000, null=True)),
                ('link', models.TextField(blank=True, max_length=2000, null=True)),
                ('date', models.TextField(blank=True, max_length=2000, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sale.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.TextField(blank=True, default='0', max_length=2000)),
                ('date', models.TextField(blank=True, default='0', max_length=2000)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sale.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
